services:
  - type: web
    name: abhirup-portfolio
    runtime: node
    plan: free
    buildCommand: npm install && npm run build:all
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
